url: http://intelligentagents.github.io
baseurl: /easy/
basepic: /easy/

# Site settings
title: Easy Group
email: easy@ic.ufal.br
description: "Easy Group"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FED136
  secondary: FEC503
  secondary-dark: 333

# Navigation
navigationLinks:
 - {permalink: "/easy/", text: "Home"}
 - {permalink: "/easy/members/", text: "Members"}
 - {permalink: "/easy/projects/", text: "Projects"}
 - {permalink: "/easy/partners/", text: "Partners"}
 - {permalink: "/easy/contact/", text: "Contact"}

# Team names, titles and social links
people:
- name: Baldoino Fonseca dos Santos Neto
  pic: 1
  position: PhD
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Davi Bibiano Brito
  pic: 2
  position: PhD
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Joilson Batista de Almeida Rêgo
  pic: 3
  position: PhD
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Márcio de Medeiros Ribeiro
  pic: 4
  position: PhD
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Thiago Damasceno Cordeiro
  pic: 5
  position: Master
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Tiago Figueiredo Vieira
  pic: 6
  position: PhD
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/easyufal
  - title: facebook
    url: https://www.facebook.com/engineeringandsystems/

# Build settings
markdown: kramdown
permalink: pretty

