url: https://y7kim.github.io
baseurl:

# Site settings
title: EASY GROUP
email: easy@ic.ufal.br
description: "EASY GROUP"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FED136
  secondary: FEC503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Baldoino Fonseca dos Santos Neto
  pic: 1
  position: Doctor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Davi Bibiano Brito
  pic: 2
  position: Doctor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Joilson Batista de Almeida Rêgo
  pic: 3
  position: Doctor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Márcio de Medeiros Ribeiro
  pic: 1
  position: Doctor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Thiago Damasceno Cordeiro
  pic: 1
  position: Master
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Tiago Figueiredo Vieira
  pic: 1
  position: Doctor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/easyufal
  - title: facebook
    url: https://www.facebook.com/engineeringandsystems/

# Build settings
markdown: kramdown
permalink: pretty
